name: Validate Code

on: pull_request

jobs:
  validate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [10.x, 11.x, 12.x]

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: install dependencies
        run: npm install --no-save
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: lint commits
        run:
          npx commitlint --config="./src/config/commitlint.config.js" --from="origin/${{
          github.base_ref }}" --to="origin/${{ github.head_ref }}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: npm run build
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: lint js
        run: npm run lint
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: run tests
        run: npm run test
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          CI: true
